import './globals.css';
import { Inter } from 'next/font/google';
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import "primereact/resources/themes/lara-light-cyan/theme.css";
import 'primereact/resources/themes/lara-light-indigo/theme.css';   // theme
import 'primeflex/primeflex.css';                                   // css utility
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.css';
import './flags.css'
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Jhigu Family Genealogy',
  description: 'Generated by next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeReactProvider value={{ unstyled: false }}>{children}</PrimeReactProvider>
      </body>
    </html>
  );
}
